version: '3.8'

services:
  app:
    image: ${DOCR_REGISTRY}/${APP_REPOSITORY}:${GITHUB_RUN_NUMBER}
    volumes:
      - /etc/ssl/certs/cert.pem:/etc/ssl/certs/cert.pem:ro
      - /etc/ssl/private/key.pem:/etc/ssl/private/key.pem:ro
    environment:
      - SSL_CERT_PATH=/etc/ssl/certs/cert.pem
      - SSL_KEY_PATH=/etc/ssl/private/key.pem
    depends_on:
      db:
        condition: service_healthy

  db:
    image: ${DOCR_REGISTRY}/${DB_REPOSITORY}:${GITHUB_RUN_NUMBER}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=%
      - MYSQL_TCP_PORT=3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 15