version: '3.8'

services:
  app:
    image: ${DOCR_REGISTRY}/${APP_REPOSITORY}:${GITHUB_RUN_NUMBER}
    volumes:
      - /etc/ssl/certs/cert.pem:/etc/ssl/certs/cert.pem
      - /etc/ssl/private/key.pem:/etc/ssl/private/key.pem
    environment:
      - SSL_CERT_PATH=/etc/ssl/certs/cert.pem
      - SSL_KEY_PATH=/etc/ssl/private/key.pem
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:443/health"] 

  db:
    image: your-registry/db-image:tag
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - mysql_sock:/run/mysqld
    healthcheck:
      test: ["CMD-SHELL", "[ -f /etc/ssl/certs/cert.pem ] && [ -f /etc/ssl/private/key.pem ]"]
      interval: 10s
      timeout: 5s
      retries: 5