version: '3.8'

services:
  app:
    image: ${DOCR_REGISTRY}/${APP_REPOSITORY}:${GITHUB_RUN_NUMBER}
    ports:
      - "443:443"
    volumes:
      - .:/usr/src/app
    env_file: 
      - .env
    depends_on:
      - db

  db:
    image: ${DOCR_REGISTRY}/${DB_REPOSITORY}:${GITHUB_RUN_NUMBER}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - mysql_sock:/run/mysqld  # Add this line
    # ... rest of your config

volumes:
  db_data:
  mysql_sock:  # Declare the volume
