FROM alpine:3.18
RUN apk add --no-cache mariadb mariadb-client bash
RUN mkdir -p /run/mysqld && chown -R mysql:mysql /run/mysqld
COPY entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]